const Images = {
	image_gallery_cone: require("./desktop/image-gallery-cone.jpg"),
	image_header: require("./desktop/image-header.jpg").default,
	icon_arrow_down: require("./icon-arrow-down.svg").default,
	image_transform: require("./desktop/image-transform.jpg").default,
	image_stand_out: require("./desktop/image-stand-out.jpg").default,
	image_photography: require("./desktop/image-photography.jpg").default,
	image_graphic_design: require("./desktop/image-graphic-design.jpg").default,
	image_emily: require("./image-emily.jpg").default,
	image_jennie: require("./image-jennie.jpg").default,
	image_thomas: require("./image-thomas.jpg").default,
	image_1: require("./desktop/image-gallery-cone.jpg").default,
	image_2: require("./desktop/image-gallery-milkbottles.jpg").default,
	image_3: require("./desktop/image-gallery-orange.jpg").default,
	image_4: require("./desktop/image-gallery-sugarcubes.jpg").default,
	image_fb: require("./icon-facebook.svg").default,
	image_insta: require("./icon-instagram.svg").default,
	image_pinterest: require("./icon-pinterest.svg").default,
	image_twitter: require("./icon-twitter.svg").default,
	image_hamburger: require("./icon-hamburger.svg").default,

	image_1_mobile: require("./mobile/image-gallery-cone.jpg").default,
	image_2_mobile: require("./mobile/image-gallery-milkbottles.jpg").default,
	image_3_mobile: require("./mobile/image-gallery-orange.jpg").default,
	image_4_mobile: require("./mobile/image-gallery-sugar-cubes.jpg").default,
	image_transform_mobile: require("./mobile/image-transform.jpg").default,
	image_stand_out_mobile: require("./mobile/image-stand-out.jpg").default,
	image_photography_mobile: require("./mobile/image-photography.jpg").default,
	image_graphic_design_mobile: require("./mobile/image-graphic-design.jpg")
		.default,
	image_gallery_cone_mobile: require("./mobile/image-gallery-cone.jpg").default,
	image_header_mobile: require("./mobile/image-header.jpg").default,
};

export default Images;
